package mu.edu.equals.Student.mutable;

import java.util.HashMap;
import java.util.Map;

public class Main {

	public static void main(String[] args) {

		Map<Student, String> grades = new HashMap<>();
		
		Student s1 = new Student(1, "Alice");

		grades.put(s1, "A");
		
		s1.setID(2);
		
		Student s2 = new Student(2, "Alice");
		
		System.out.println(grades.get(s1));
		System.out.println(grades.get(s2));
		
		/***
		 * This may fail to find the entry 
		 * correctly because the object's 
		 * hash code changed after insertion.
		 * 
		 * 
		 * Fields used in equals() and hashCode() 
		 * should ideally be stable while the object 
		 * is used in a hash-based collection.
		 * Immutability should be a target!
		 * Using autogenerated ID key with static ID variable.
		 * Not providing setID method.
		 * 
		 */
		
//		Student s2 = new Student(1, "Alice");
//
//		System.out.println(grades.get(s2));
		
	}

}
